CREATE TABLE WALLPAPER (
    WALL_ID VARCHAR(50) NOT NULL,
    WALL_WIDTH INTEGER NOT NULL,
    WALL_HEIGHT INTEGER NOT NULL,
    WALL_FILE_SIZE BIGINT NOT NULL,
    WALL_HASH BIGINT NOT NULL,
    WALL_UPLOAD_DATE TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX PK_WALL ON WALLPAPER(WALL_ID);
ALTER TABLE WALLPAPER ADD PRIMARY KEY (WALL_ID);

CREATE TABLE WALLPAPER_COLOR (
    WACO_ID VARCHAR(50) NOT NULL,
    WACO_WALL_ID VARCHAR(50) NOT NULL,
    WACO_ORDER INTEGER NOT NULL,
    WACO_RED INTEGER NOT NULL,
    WACO_GREEN INTEGER NOT NULL,
    WACO_BLUE INTEGER NOT NULL,
    WACO_CIE_L DOUBLE NOT NULL,
    WACO_CIE_A DOUBLE NOT NULL,
    WACO_CIE_B DOUBLE NOT NULL
);

CREATE UNIQUE INDEX PK_WACO ON WALLPAPER_COLOR(WACO_ID);
ALTER TABLE WALLPAPER_COLOR ADD PRIMARY KEY (WACO_ID);

ALTER TABLE WALLPAPER_COLOR ADD FOREIGN KEY (WACO_WALL_ID) REFERENCES WALLPAPER(WALL_ID);