CREATE TABLE TAG (
    TAG_ID              VARCHAR(50) NOT NULL,
    TAG_NAME            VARCHAR(50) NULL,
    TAG_TYPE            VARCHAR(4) NOT NULL,
    TAG_CREATION_DATE   TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX PK_TAG ON TAG(TAG_ID);
ALTER TABLE TAG ADD PRIMARY KEY (TAG_ID);

CREATE TABLE TAG_WALLPAPER (
    TAG_ID      VARCHAR(50) NOT NULL,
    WALL_ID     VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX PK_TAGA ON TAG_WALLPAPER(TAG_ID, WALL_ID);
ALTER TABLE TAG_WALLPAPER ADD PRIMARY KEY (TAG_ID, WALL_ID);
